name: "Garry's Mod Workshop Upload"
author: 'dhkatz'
description: "Upload an addon to the Garry's Mod Steam Workshop."

branding:
  icon: 'arrow-up-circle'
  color: 'blue'

inputs:
  username:
    description: 'Steam username'
    required: true
    default: 'anonymous'

  password:
    description: 'Steam password'
    required: false
  totp:
    description: 'Steam TOTP code'
    required: false
  vdf:
    description: 'Steam account VDF'
    required: false

  id:
    description: 'Addon ID'
    required: true

  changelog:
    description: 'Addon changelog'
    required: false
  markdown-changelog:
    description: 'Addon changelog (Markdown)'
    required: false

  icon:
    description: 'Addon icon'
    required: false
  title:
    description: 'Addon title'
    required: false
  description:
    description: 'Addon description'
    required: false
  markdown-description:
    description: 'Addon description (Markdown)'
    required: false
  visibility:
    description: 'Addon visibility'
    required: false

  folder:
    description: 'Addon directory'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
